= Parent POM
:toc: preamble
:toclevels: 2

:uri-build-status: https://github.com/agility-it-services/parent-pom/actions
:img-build-status: https://github.com/agility-it-services/parent-pom/actions/workflows/release.yml/badge.svg
:uri-quality-gateway: https://sonarcloud.io/dashboard?id=agility-it-services_parent-pom
:img-quality-gateway: https://img.shields.io/sonar/quality_gate/nl.agility-it-services.maven_parent-pom?label=Quality%20Gate&logo=sonarcloud&server=https%3A%2F%2Fsonarcloud.io&sonarVersion=8.2
:uri-version: https://github.com/agility-it-services/parent-pom/actions
:img-version: https://img.shields.io/github/v/release/agility-it-services/parent-pom?label=Version&logo=github
image:{img-build-status}[Build Status Badge,link={uri-build-status}] image:{img-quality-gateway}[Quality Gateway Badge,link={uri-quality-gateway}] image:{img-version}[Version Badge,link={uri-version}]

== Introduction
This Maven POM is the root POM for all our Maven projects.

In this POM the following configuration is managed for all derived Maven projects:

* Java version
* Spring Boot version
* Spring Cloud version
* Maven plugin versions
* Maven dependency versions

Also, the Maven lifecycle steps are configured to enable:

* Trunk-based development using CI friendly Maven versions

== Usage
Just add the root POM as a parent to your Maven project, replacing the version number with the actual latest version
number.

    <parent>
        <groupId>nl.agility-it-services.maven</groupId>
        <artifactId>parent-pom</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

== Code Coverage Reports
Code Coverage Reports are generated by default.

=== Unit tests
Before the unit tests are executed, JaCoCo is instrumented to measure and report the unit test coverage as a result of executing the unit tests.

The coverage report can be viewed by opening the `index.html` file located at the following location: *target/site/jacoco*

=== Integration tests
Before the integration tests are executed, JaCoCo is instrumented to measure and report the integration test coverage as a result of executing the integration tests.

The coverage report can be viewed by opening the `index.html` file located at the following location: *target/site/jacoco-it*

=== Merged code coverage report
In addition to calculating and reporting the unit test and integration test coverage, both the _unit test code coverage_ report and the _integration test
code coverage_ report are merged into a _merged code coverage_ report.

This merged code coverage report can be viewed by opening the `index.html` file located at the following location: *target/site/jacoco-merged*

The merged code coverage report is particularly useful for looking at the combined coverage of both _unit tests_ and _integration tests_.

== Maven Profiles
Besides managing dependency/plugin versions and configuring the plugins used in the build process, this Maven POM also contains a number of useful profiles
which can be enabled (or in some cases are already enabled by default) at will during local development and/or are used in our CI/CD pipelines.

=== verify-release-notes
Verify whether the latest release in the `changes.xml` file is in sync with the current version of the `pom.xml` file.

==== Activation
The _verify-release-notes_ profile is activated automatically when a `changes.xml` file exists at the following location: *src/changes*.

The reasoning here is that whenever a `changes.xml` file is present, it's contents should be verified to avoid possible build failures when trying to send a release announcement to our stakeholders later in the build process.

==== Configuration
The _verify-release-notes_ profile is configured to skip verifying `SNAPSHOT` releases.

==== Reports
There are no reports generated.

Either verification is successful and the build continues or verification fails and results in a build failure as a consequence.

=== prepare-release-announcement
Prepare the release announcement to be sent out to our stakeholders.

==== Activation
The _prepare-release-announcement_ profile can be run by executing the following command:

`mvn -Pprepare-release-announcement generate-resources`

==== Configuration
The _prepare-release-announcement_ profile is configured to use the `maven-changes-templates` dependency containing the actual release announcement template to use.

Data from the Maven Changes plugin configuration in this profile and data from the project's `changes.xml` file is merged into a final release announcement.

[NOTE]
This profile will only create the final release announcement. The actual delivery of the release announcement is done from within our CI/CD pipeline.

==== Reports
The generated release announcement can be viewed by opening the `release-announcement.json` file located at the following location: *target/announcement*

=== check-for-updates
Check for any available dependency version updates.

==== Activation
The _check-for-updates_ profile can be run by executing the following command:

`mvn -Pcheck-for-updates validate`

==== Configuration
The _check-for-updates_ profile is configured to check the following for possible version updates:

* Parent POM versions
* Plugin versions
* Dependency versions

[NOTE]
This profile is configured to only _report_ possible version updates. It is _not_ going to actually apply them in case there are any.

==== Reports
Available updates can be viewed as part of the console output.

Available updates can also be viewed by opening the `outdated-dependencies.txt` file located at the following location: *target*

The report is particularly useful for detecting possible major version upgrades, since automated version updates do _not_ take major versions into account, because these are incompatible by definition.

=== update-versions
Apply any available dependency version updates.

==== Activation
The _update-versions_ profile can be run by executing the following command:

`mvn -Pupdate-versions validate`

==== Configuration
The _update-versions_ profile is configured to update:

* Parent POM versions
* Plugin versions
* Dependency versions

[NOTE]
This profile is configured to actually apply any available update to the project's `pom.xml` file.

[NOTE]
This profile is configured to _NOT_ take major version updates into account due to the simple fact that major version upgrades are incompatible by definition and therefore most likely need code and/or configuration changes before they can be used.

==== Reports
Applied updates can be viewed as part of the console output.

=== dependency-check
Run the OWASP Dependency-check to scan for known vulnerabilities.

==== Activation
The _dependency-check_ profile can be run by executing the following command:

`mvn -Pdependency-check validate`

The _dependency-check_ profile is also activated as part of the build when the `all-profiles` system property is passed to a Maven build command, for example:

`mvn -Dall-profiles install`

==== Configuration
The _dependency-check_ profile is configured to never fail the build in case of an error while analyzing a project's dependencies.

==== Reports
The analysis report can be viewed as part of the console output.

The analysis report can also be viewed as a single page website by opening the `dependency-check-report.html` file located at the following location: *target*

[NOTE]
In addition to the single page website a JSON report file is generated. Both of which are used in our CI/CD pipeline to include the full details of the analysis report in SonarQube where it can be examined as well.

=== mutation-test
Run mutation tests.

==== Activation
The _mutation-test_ profile can be run by executing the following command:

`mvn -Pmutation-test test`

==== Configuration
The _mutation-test_ profile is configured to run the mutation analysis on the local copy of the codebase, including any local changes.

==== Reports
The analysis report can be viewed by opening the `index.html` file located at the following location: *target/pit-reports*

[NOTE]
In addition to the analysis report HTML file an XML report file is generated which is used in our CI/CD pipeline to include the analysis report in SonarQube where it can be examined as well.
